Snowfall.Web.Mvc/Models/Evenements/EvenementsIndexViewModel.cs
using Snowfall.Domain.Models;

namespace Snowfall.Web.Mvc.Models.Evenements;

public class EvenementsIndexViewModel
{
    public required List<Evenement> Evenements { get; set; }

    public required List<Ville> Villes { get; set; }

    public int? FiltreVilleId { get; set; }

    public required List<FourchettePrix> FourchettePrix { get; set; }

    public required int? FiltreFourchettePrixId { get; set; }
}

Snowfall.Web.Mvc/Controllers/EvenementsController.cs
using Microsoft.AspNetCore.Mvc;
using Snowfall.Application.Services;
using Snowfall.Domain.Models;
using Snowfall.Web.Mvc.Models.Evenements;

namespace Snowfall.Web.Mvc.Controllers;

[Route("[controller]")]
public class EvenementsController : Controller
{
    private IEvenementService _evenementService;
    private readonly IVilleService _villeService;
    
    public EvenementsController(
        IEvenementService evenementService,
        IVilleService villeService)
    {
        _evenementService = evenementService;
        _villeService = villeService;
    }
    
    [Route("/")]
    public async Task<IActionResult> Index(int? ville, int? fourchette)
    {
        List<Evenement> evenements = await _evenementService.FindByVilleIdEtFourchettePrix(ville, fourchette);
        List<Ville> villes = await _villeService.GetAll();
        
        var viewModel = new EvenementsIndexViewModel
        {
            Villes = villes,
            Evenements = evenements,
            FiltreVilleId = ville,
            FourchettePrix = FourchettePrix.FourchettePrixGlobale,
            FiltreFourchettePrixId = fourchette
        };
    
        return View(viewModel);
    }
    
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Show(int id, string? option)
    {
        Evenement? evenement = await _evenementService.FindById(id);
        if (evenement == null)
        {
            return NotFound(); 
        }

        return View(evenement);
    }
    
    [HttpGet("{id:int}/edit")]
    public IActionResult Edit(int id)
    {
        return Content("Vue Edit de EvenementsController, id: " + id);
    }
}

Snowfall.Web.Mvc/Controllers/InscriptionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Snowfall.Application.Services;
using Snowfall.Domain.Models;
using Snowfall.Web.Mvc.Models.Inscriptions;

namespace Snowfall.Web.Mvc.Controllers;

[Route("[controller]")]
public class InscriptionsController : Controller
{
    private readonly IEvenementService _evenementService;
    private readonly IInscriptionService _inscriptionService;
    private readonly IPrixService _prixService;
    private readonly UserManager<ApplicationUser> _userManager;

    public InscriptionsController(
        IEvenementService evenementService,
        IInscriptionService inscriptionService,
        IPrixService prixService,
        UserManager<ApplicationUser> userManager)
    {
        _evenementService = evenementService;
        _inscriptionService = inscriptionService;
        _userManager = userManager;
        _prixService = prixService;
    }
    
    [HttpPost("[action]")]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Acheter(int id)
    {
        var evenement = await _evenementService.FindById(id);

        if (evenement == null) return BadRequest();

        HttpContext.Session.SetInt32("Panier", id); 
        
        return RedirectToAction(nameof(Checkout));
    }
    
    [HttpPost("[action]")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AcheterPlusTard(int id)
    {
        var evenement = await _evenementService.FindById(id);

        if (evenement == null) return BadRequest();

        HttpContext.Session.SetInt32("Panier", id); 
        
        return RedirectToAction("Connexion", "Auth", new { returnUrl = "Inscriptions/Checkout" });
    }
    
    [HttpGet("[action]")]
    [Authorize]
    public async Task<IActionResult> Checkout()
    {
        var evenementId = HttpContext.Session.GetInt32("Panier");

        if (evenementId.HasValue && User.Identity?.Name != null)
        {
            var evenement = await _evenementService.FindById(evenementId.Value);
            var utilisateur = await _userManager.FindByNameAsync(User.Identity.Name);
        
            if (evenement == null || utilisateur == null)
                return BadRequest();

            Prix prix = _prixService.CalculerPrix(evenement); 
            
            var viewModel = new InscriptionViewModel()
            {
                Utilisateur = utilisateur,
                Evenement = evenement,
                Prix = prix
            };
        
            return View(viewModel);
        }

        return RedirectToAction("Index", "Evenements");
    }
    
    [HttpDelete]
    [Authorize]
    [ValidateAntiForgeryToken]
    public IActionResult Delete()
    {
        HttpContext.Session.Remove("Panier"); 

        return RedirectToAction("Index", "Evenements");
    }
}

Snowfall.Web.Mvc/Controllers/MessagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Snowfall.Application.Services;
using Snowfall.Domain.Models;
using Snowfall.Web.Mvc.Extensions;
using Snowfall.Web.Mvc.Models.Messages;

namespace Snowfall.Web.Mvc.Controllers;

[Route("evenements/{evenementId:int}/[controller]")] 
public class MessagesController : Controller
{
    private readonly IMessageService _messageService; 
    private readonly IEvenementService _evenementService;

    public MessagesController(
        IMessageService messageService,
        IEvenementService evenementService) 
    { 
        _messageService = messageService;
        _evenementService = evenementService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(int evenementId) 
    {
        List<Message> messages = await _messageService.FindByEvenementId(evenementId);
        return PartialView("_Messages", messages);
    }
    
    [HttpGet("[action]")]
    [Authorize]
    public async Task<IActionResult> New(int evenementId)
    {
        var evenement = await _evenementService.FindById(evenementId); 
        if (evenement == null) return NotFound(); 
        
        var viewModel = new CreerMessageViewModel()
        {
            EvenementId = evenementId
        };
        return View(viewModel);
    }
    
    [HttpPost]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int evenementId, CreerMessageViewModel viewModel)
    {
        var evenement = await _evenementService.FindById(evenementId);
        if (evenement == null) return NotFound();
        
        if (!ModelState.IsValid) 
        { 
            return View(nameof(New), viewModel); 
        } 
        
        Message message = new ()
        {
            UtilisateurId = User.Identity!.Id(),
            EvenementId = viewModel.EvenementId,
            Contenu = viewModel.Contenu
        };

        await _messageService.Create(message);

        return RedirectToAction("Show", "Evenements", new { Id = evenementId });
    }
    
    [HttpGet("{id:int}/edit")]
    [Authorize]
    public async Task<IActionResult> Edit(int id, int evenementId)
    {
        var message = await ObtenirMessage(id, evenementId);
        if (message == null) return NotFound();
    
        var viewModel = new ModifierMessageViewModel
        {
            Id = message.Id,
            EvenementId = message.EvenementId,
            Contenu = message.Contenu
        };

        return View(viewModel);
    }
    
    [HttpPatch("{id:int}")]
    [Authorize]
    public async Task<IActionResult> Update(int id, int evenementId, ModifierMessageViewModel viewModel)
    {
        var message = await ObtenirMessage(id, evenementId);
        if (message == null) return NotFound();   
        
        if (!ModelState.IsValid)
        {
            return View(nameof(Edit), viewModel);
        }

        message.Contenu = viewModel.Contenu;
        await _messageService.Update(message);
    
        return RedirectToAction("Show", "Evenements", new { id = evenementId});
    }
    
    [HttpGet("{id:int}/[action]")]
    [Authorize]
    public async Task<IActionResult> ConfirmationDelete(int evenementId, int Id)
    {
        var message = await _messageService.FindById(Id);

        if (message == null) return NotFound();
        
        return PartialView("_ModalConfirmationDelete", message);
    }
    
    [HttpDelete("{id:int}")]
    [Authorize]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, int evenementId)
    {
        var message = await ObtenirMessage(id, evenementId);
        if (message == null) return NotFound();

        await _messageService.Delete(message.Id);
    
        return RedirectToAction("Show", "Evenements", new { id = evenementId});
    }
    
    private async Task<Message?> ObtenirMessage(int id, int evenementId)
    {
        var evenement = await _evenementService.FindById(evenementId);
        var message = await _messageService.FindById(id);

        if (evenement == null || message == null) return null;
        if (message.UtilisateurId != User.Identity?.Id()) return null;

        return message;
    }
}

Snowfall.Web.Mvc/Views/Evenements/Index.cshtml
@model EvenementsIndexViewModel;

@{
    ViewBag.Title = "Événements";
}

<h1 class="mb-4">Événements</h1>

<div class="row">
    <div class="col-lg-3 mb-4">
        @* <form asp-controller="Evenements" asp-action="Index"> *@
        @*     <button class="btn btn-primary">S'inscrire</button> *@
        @* </form> *@
        <h6 class="text-uppercase">Filtrer par ville</h6>
        <div class="list-group">
            @foreach (Ville ville in Model.Villes)
            {
                <a class="list-group-item list-group-item-action @(Model.FiltreVilleId == ville.Id ? "active" : string.Empty)"
                   asp-controller="Evenements"
                   asp-action="Index"
                   asp-route-fourchette="@Model.FiltreFourchettePrixId"
                   asp-route-ville="@ville.Id">
                    @ville.Nom, @ville.PaysIso
                </a>
            }
        </div>
        <h6 class="text-uppercase mt-3">Filtrer par prix</h6>
        <div class="list-group">
            @foreach (FourchettePrix fourchette in Model.FourchettePrix)
            {
                <a class="list-group-item list-group-item-action @(Model.FiltreFourchettePrixId == fourchette.Id ? "active" : string.Empty)"
                   asp-controller="Evenements"
                   asp-action="Index"
                   asp-route-ville="@Model.FiltreVilleId"
                   asp-route-fourchette="@fourchette.Id">
                    @fourchette.Nom
                </a>
            }
        </div>
        <a class="btn btn-secondary mt-3"
           asp-controller="Evenements"
           asp-action="Index">
            Réinitialiser les filtres
        </a>
    </div>
    <div class="col-lg-9">
        <div class="row">
            @foreach (Evenement evenement in Model.Evenements)
            {
                <partial name="_Evenement" model="evenement"/>
            }
        </div>
    </div>
</div>

Snowfall.Web.Mvc/Views/Evenements/Show.cshtml
@model Evenement

@{
    ViewBag.Title = Model.Nom;
    Layout = "_Layout";
}

<h1 class="mb-3">@Model.Nom - Id: @Model.Id</h1>

<div class="row">
    <div class="col-md-6">
        @if (@Model.ImagePath != null)
        {
            <img class="img-fluid img-thumbnail" src="~/images/evenements/@Model.ImagePath" />
        }
    </div>
    
    <div class="col-md-6">
        <p>@Model.Description</p>
        <p><strong>@Model.Prix$</strong></p>
        <ul class="list-unstyled small">
            <li>Date: @Model.Date.ToShortDateString()</li>
            <li>Capacité: @Model.Capacite places</li>
        </ul>
        
        <partial name="_Ville" model="@Model.Ville"/>
        
        @if (User.Identity?.IsAuthenticated == true)
        {
            <form asp-controller="Inscriptions" asp-action="Acheter">
                <input type="hidden" asp-for="Id"></input>
                <button class="btn btn-primary mt-5">Acheter un billet</button>
            </form>
        }
        else
        {
            <form asp-controller="Inscriptions" asp-action="AcheterPlusTard">
                <input type="hidden" asp-for="Id"></input>
                <button class="btn btn-primary mt-5">Connectez-vous pour acheter</button>
            </form>
        }
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-8">
        <div class="d-flex mb-3">
            <div class="flex-grow-1">
                <h2>Messages</h2>
            </div>
            <div>
                @if (User.Identity?.IsAuthenticated == true)
                {
                    <a class="btn btn-secondary"
                       asp-controller="Messages"
                       asp-route-evenementId="@Model.Id"
                       asp-action="New">
                        Écrire un message
                    </a>
                }
            </div>
        </div>
        
        <div hx-get                    
            hx-controller="Messages"   
            hx-action="Index"          
            hx-route-evenementId="@Model.Id"
            hx-trigger="load">
        </div>
    </div>
</div>

<a class="btn btn-secondary mt-4" asp-controller="Evenements" asp-action="">Retour à la liste</a>

Snowfall.Web.Mvc/Views/Evenements/_Evenement.cshtml
@model Evenement

<div class="col-md-6 col-lg-4 mb-4">
    <div class="card h-100">
        @if (@Model.ImagePath != null)
        {
            <img class="card-evenement img-fluid rounded-top object-fit-cover" src="~/images/evenements/@Model.ImagePath"/>
        }
        <div class="card-body">
            <h5 class="card-title">@Model.Nom</h5>
            <p class="card-text">@Model.Description</p>
            <p class="card-text">@Model.Prix$</p>
            <p class="card-text">
                <small class="text-muted">@Model.Date.ToShortDateString() - @Model.Capacite places</small>
            </p>
            @if (@Model.Ville != null)
            {
                <p class="card-text">
                    <partial name="_Ville" model="@Model.Ville"/>
                </p>
            }
        </div>
        <div class="card-footer">
            <a class="btn btn-primary"
               asp-controller="Evenements"
               asp-action="Show"
               asp-route-id="@Model.Id">
                Détails
            </a>
        </div>
    </div>
</div>

Snowfall.Web.Mvc/Views/Evenements/_Ville.cshtml
@model Ville

<span class="badge text-bg-light">@Model.Afficher()</span>