Snowfall.Web.Mvc/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Snowfall.Domain.Models;
using Snowfall.Web.Mvc.Models.Auth;

namespace Snowfall.Web.Mvc.Controllers;

[Route("[controller]")]
public class AuthController : Controller
{
    private readonly SignInManager<ApplicationUser> _signInManager;
    
    public AuthController(SignInManager<ApplicationUser> signInManager)
    {
        _signInManager = signInManager;
    }
    
    // GET /auth/connexion
    [HttpGet("[action]")]
    public IActionResult Connexion(string? returnUrl)
    {
        if (!string.IsNullOrWhiteSpace(returnUrl))
        {
          ViewBag.ReturnUrl = returnUrl;
        }
        return View();
    }
    
    // GET /auth/deconnexion
    [HttpPost("[action]")]
    [Authorize]
    public async Task<IActionResult> Deconnexion()
    {
        await _signInManager.SignOutAsync();
        HttpContext.Session.Clear(); 
        
        return RedirectToAction("Index", "Evenements");
    }
    
    // POST /auth
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Authentifier(ConnexionViewModel viewModel, string? returnUrl)
    {
        if (ModelState.IsValid)
        {
            var result = await _signInManager.PasswordSignInAsync(
                viewModel.Email,
                viewModel.Password,
                true,
                lockoutOnFailure: false
            );

            if (result.Succeeded)
            {
                if (!string.IsNullOrWhiteSpace(returnUrl))
                {
                    return Redirect(returnUrl);
                }

                return RedirectToAction("Index", "Evenements");
            }

            ModelState.AddModelError("Authentification.Echec", Resources.Controllers.AuthController.Authentification_Echec);
            return View(nameof(Connexion), viewModel);
        }
        
        return View(nameof(Connexion), viewModel);
    }
}

Snowfall.Web.Mvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Snowfall.Web.Mvc.Extensions
@{
    var action = ViewContext.RouteData.Values["Action"]?.ToString();
    var controller = ViewContext.RouteData.Values["Controller"]?.ToString();
}
<!DOCTYPE html>
<html lang="fr" data-bs-theme="dark">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Snowfall</title>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    <environment names="Development">
        <!-- Vite dev server -->
        <script type="module" src="http://localhost:5174/assets/js/app.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script type="module" crossorigin asp-src-include="~/dist/assets/app-*.js"></script>
        <link rel="stylesheet" asp-href-include="~/dist/assets/app-*.css"/>
    </environment>
    <link rel="stylesheet" href="~/Snowfall.Web.Mvc.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="" asp-action="">Snowfall</a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a
                            class="nav-link @(controller == "Evenements" && action == "Index" ? "active" : "")"
                            asp-controller=""
                            asp-action="">
                            Accueil
                        </a>
                    </li>
                </ul>
                @if (User.Identity!.IsAuthenticated)
                {
                    <span class="navbar-text">Bonjour, @User.Identity.Prenom()</span>  
                }
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <form asp-controller="Auth" asp-action="Deconnexion">
                                <button class="btn btn-link nav-link">Déconnexion</button>
                            </form>
                        </li>
                        
                        @if (Context.Session.GetInt32("Panier").HasValue && controller != "Inscriptions")
                        {
                            <li class="nav-item">
                                <a asp-controller="Inscriptions" asp-action="Checkout" class="btn btn-outline-primary nav-link">
                                    Passer à la caisse
                                </a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item">
                            <a
                                class="nav-link @(controller == "Auth" ? "active" : String.Empty)"
                                asp-controller="Auth"
                                asp-action="Connexion">
                                Connexion
                            </a>
                        </li>

                        <li class="nav-item">
                            <a
                                class="nav-link @(controller == "Comptes" ? "active" : String.Empty)"
                                asp-controller="Comptes"
                                asp-action="New">
                                Inscription
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Snowfall
    </div>
</footer>

<div id="app-modal-manager"
     _="on htmx:afterSettle 
        call bootstrap.Modal.getOrCreateInstance('#app-modal').show()">
</div>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>