Snowfall.Web.Mvc/Models/Comptes/CreerCompteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Snowfall.Web.Mvc.Models.Comptes;

#nullable disable
public class CreerCompteViewModel
{
    [Required(ErrorMessage = "Prenom.Required")] 
    [Display(Name = "Prénom", Prompt = "Prénom")]
    public string Prenom { get; set; }
    
    [Required(ErrorMessage = "Nom.Required")] 
    [Display(Name = "Nom", Prompt = "Nom")]
    public string Nom { get; set; }
    
    [Required(ErrorMessage = "Adresse.Required")]
    [Display(Name = "Adresse", Prompt = "Adresse")]
    public required string Adresse { get; set; }

    [Required(ErrorMessage = "Ville.Required")]
    [Display(Name = "Ville", Prompt = "Ville")]
    public required string Ville { get; set; }

    [Required(ErrorMessage = "CodePostal.Required")]
    [Display(Name = "Code postal", Prompt = "Code postal")]
    public required string CodePostal { get; set; }

    [Required(ErrorMessage = "Province.Required")]
    [Display(Name = "Province", Prompt = "Province")]
    public required string Province { get; set; }

    [Required(ErrorMessage = "Pays.Required")]
    [Display(Name = "Pays", Prompt = "Pays")]
    public required string Pays { get; set; }

    [Required(ErrorMessage = "Email.Required")] 
    [EmailAddress]
    [Display(Name = "Courriel", Prompt = "Courriel")]
    public string Email { get; set; }
    
    [Required(ErrorMessage = "Password.Required")] 
    [StringLength(16, MinimumLength = 8, ErrorMessage = "Password.Length")]
    [DataType(DataType.Password)]
    [Display(Name = "Mot de passe", Prompt = "Mot de passe")]
    public string Password { get; set; }
    
    [Required(ErrorMessage = "ConfirmPassword.Required")] 
    [DataType(DataType.Password)]
    [Compare("Password", ErrorMessage = "Password.Compare")] 
    [Display(Name = "Confirmation du mot de passe", Prompt = "Confirmation du mot de passe")]
    public string ConfirmPassword { get; set; }
}

Snowfall.Web.Mvc/Controllers/ComptesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Snowfall.Domain.Models;
using Snowfall.Web.Mvc.Models.Comptes;

namespace Snowfall.Web.Mvc.Controllers;
[Route("[controller]")]
public class ComptesController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;

    public ComptesController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    [HttpGet("[action]")]
    public IActionResult New()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreerCompteViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            var user = new ApplicationUser()
            {
                UserName = viewModel.Email,
                Email = viewModel.Email,
                Prenom = viewModel.Prenom,
                Nom = viewModel.Nom,
                Client = new Client
                {
                    Adresse = viewModel.Adresse,
                    Ville = viewModel.Ville,
                    CodePostal = viewModel.CodePostal,
                    Province = viewModel.Province,
                    Pays = viewModel.Pays
                }
            };
            
            IdentityResult result = await _userManager.CreateAsync(user, viewModel.Password);
            
            if (result.Succeeded) 
            { 
                string role = "Utilisateur";
                await _userManager.AddToRoleAsync(user, role);
                await _signInManager.SignInAsync(user, isPersistent: true); 
                return RedirectToAction("Index", "Evenements"); 
            } 
        }
    
        return View(nameof(New), viewModel);
    }
}

Snowfall.Web.Mvc/Views/Comptes/New.cshtml
@model Snowfall.Web.Mvc.Models.Comptes.CreerCompteViewModel

@{
    ViewBag.Title = "Créer un compte";
}

<div class="row">
    <div class="col-md-8 col-lg-6 offset-md-2 offset-lg-3">
        <h1 class="mb-3">Créer un compte</h1>
        
        <form asp-controller="Comptes" asp-action="Create">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Prenom" class="form-control"/>
                        <label asp-for="Prenom"></label>
                        <span asp-validation-for="Prenom" class="invalid-feedback"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Nom" class="form-control"/>
                        <label asp-for="Nom"></label>
                        <span asp-validation-for="Nom" class="invalid-feedback"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input asp-for="Adresse" class="form-control"/>
                        <label asp-for="Adresse"></label>
                        <span asp-validation-for="Adresse" class="invalid-feedback"></span>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Ville" class="form-control"/>
                        <label asp-for="Ville"></label>
                        <span asp-validation-for="Ville" class="invalid-feedback"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="CodePostal" class="form-control"/>
                        <label asp-for="CodePostal"></label>
                        <span asp-validation-for="CodePostal" class="invalid-feedback"></span>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Province" class="form-control"/>
                        <label asp-for="Province"></label>
                        <span asp-validation-for="Province" class="invalid-feedback"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Pays" class="form-control"/>
                        <label asp-for="Pays"></label>
                        <span asp-validation-for="Pays" class="invalid-feedback"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input asp-for="Email" class="form-control"/>
                        <label asp-for="Email"></label>
                        <span asp-validation-for="Email" class="invalid-feedback"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input asp-for="Password" class="form-control"/>
                        <label asp-for="Password"></label>
                        <span asp-validation-for="Password" class="invalid-feedback"></span>
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-floating mb-3">
                        <input asp-for="ConfirmPassword" class="form-control"/>
                        <label asp-for="ConfirmPassword"></label>
                        <span asp-validation-for="ConfirmPassword" class="invalid-feedback"></span>
                    </div>
                </div>

                <div class="col-12">
                    <button class="btn btn-primary">S'inscrire</button>
                </div>
            </div>
        </form>
    </div>
</div>